export const facultyData = [
  {
    department: "General Medicine",
    members: [
      { sno: "1", name: "Prof.(Dr.) S K Singh", designation: "Professor", image: "Prof.(Dr.) S K Singh.webp" },
      { sno: "2", name: "Dr. Madhukar Rai", designation: "Professor", image: "Prof.(Dr.) Madhukar Rai.webp" },
      { sno: "3", name: "Dr. M.S.I. Siddiqui", designation: "Professor", image: "Prof.(Dr.) M. S. I. Siddiqui.webp" },
      { sno: "4", name: "Dr. Nikhil Sinha", designation: "Professor" },
      { sno: "5", name: "Dr. Ashutosh Mishra", designation: "Associate Professor" },
      { sno: "6", name: "Dr. Pallavi Mishra", designation: "Associate Professor" },
      { sno: "7", name: "Dr. Rahul K Mangalam", designation: "Associate Professor" },
      { sno: "8", name: "Dr. Vinay K Singh", designation: "Associate Professor" },
      { sno: "9", name: "Dr. Haramohan Sahoo", designation: "Assistant Professor", image: "Dr. Harmohan Saho.webp" },
      { sno: "10", name: "Dr. Faraz Ahmed", designation: "Assistant Professor" },
      { sno: "11", name: "Dr. Amit Asthana", designation: "Assistant Professor" },
      { sno: "12", name: "Dr. Nilesh Rai", designation: "Assistant Professor", image: "Dr. Nilesh Kumar Rai.webp" },
      { sno: "13", name: "Dr. Yogesh Gaur", designation: "Assistant Professor", image: "Dr. Yogesh Kumar Gaur.webp" },
      { sno: "14", name: "Dr. Kumar Bhaskar", designation: "Assistant Professor" },
      { sno: "15", name: "Dr. Shobit Agrawal", designation: "Assistant Professor" },
      { sno: "16", name: "Dr. Avnish", designation: "Assistant Professor" },
      { sno: "17", name: "Dr. Jothilakshmi V", designation: "Assistant Professor" },
      { sno: "18", name: "Dr. Pankaj Ojha", designation: "Assistant Professor" },
      { sno: "19", name: "Dr. Dilip Chaursiya", designation: "Assistant Professor" },
      { sno: "20", name: "Dr.Santosh Kumar Pandey", designation: "Assistant Professor" },
      { sno: "21", name: "Dr. Rohit Singh", designation: "Assistant Professor" },
      { sno: "22", name: "Dr. Ankit Tiwari", designation: "Senior Resident" },
      { sno: "23", name: "Dr. Nilesh Kumar", designation: "Senior Resident" },
      { sno: "24", name: "Dr. Deepa", designation: "Senior Resident" },
      { sno: "25", name: "Dr. Shailendra", designation: "Senior Resident" },
      { sno: "26", name: "Dr. Sumeet Chaterjee", designation: "Senior Resident" },
      { sno: "27", name: "Dr. Somil singh", designation: "Senior Resident" },
      { sno: "28", name: "Dr. Avanish", designation: "Senior Resident" },
      { sno: "29", name: "Dr. Vishal sharma", designation: "Junior Resident" },
      { sno: "30", name: "Dr. Krishna Chandra", designation: "Junior Resident" },
      { sno: "31", name: "Dr. Himanshu Singhla", designation: "Junior Resident" },
      { sno: "32", name: "Dr. Kaushik Sarkar", designation: "Junior Resident" },
      { sno: "33", name: "Dr. Vikas Verma", designation: "Junior Resident" },
      { sno: "34", name: "Dr. Abhradhwaj Singh", designation: "Junior Resident" },
      { sno: "35", name: "Dr. Kohkeesa Mahaswini", designation: "Junior Resident" },
      { sno: "36", name: "Dr. santosh Shukla", designation: "Junior Resident" },
      { sno: "37", name: "Dr. Madhavi Pandey", designation: "Junior Resident" },
      { sno: "38", name: "Dr. Rishabh", designation: "Junior Resident" },
      { sno: "39", name: "Dr. Dilip Kumar", designation: "Junior Resident" },
      { sno: "40", name: "Dr. Samarth Gupta", designation: "Junior Resident" },
      { sno: "41", name: "DR. Pradyum", designation: "Junior Resident" },
      { sno: "42", name: "Dr. Srinivas Achaju", designation: "Junior Resident" }
    ]
  },
  {
    department: "Paediatrics",
    members: [
      { sno: "1", name: "Dr. O. P. Mishra", designation: "Professor", image: "Prof.(Dr.) O. P. Mishra.webp" },
      { sno: "2", name: "Dr. R. Narayan", designation: "Associate Professor" },
      { sno: "3", name: "Dr. Ritesh Agarwal", designation: "Associate Professor" },
      { sno: "4", name: "Dr. Deepak Kumar", designation: "Associate Professor" },
      { sno: "5", name: "Dr. Ashok Singh", designation: "Associate Professor" },
      { sno: "7", name: "Dr. Ashok Rai", designation: "Assistant Professor" },
      { sno: "8", name: "Dr. Priyanka Dua", designation: "Assistant Professor" },
      { sno: "9", name: "Dr. Nirali Shanghvi", designation: "Assistant Professor" },
      { sno: "10", name: "Dr. Deepak Jaiswal", designation: "Assistant Professor" },
      { sno: "11", name: "Dr. Divyank Pathak", designation: "Assistant Professor" },
      { sno: "12", name: "Dr. Prabhat Kumar", designation: "Assistant Professor" },
      { sno: "13", name: "Dr. Arpita Mishra", designation: "Senior Resident" },
      { sno: "14", name: "Dr. Ravi Prakash", designation: "Senior Resident" },
      { sno: "15", name: "Dr. Rahul Patel", designation: "Senior Resident" },
      { sno: "16", name: "Dr. Pravesh Yadav", designation: "Senior Resident" },
      { sno: "17", name: "Dr. Shivangi Puri", designation: "Junior Resident" },
      { sno: "18", name: "Dr. Rewati Sharma", designation: "Junior Resident" },
      { sno: "19", name: "Dr. Alok Ranjan", designation: "Junior Resident" },
      { sno: "20", name: "Dr. Rishi Sharma", designation: "Junior Resident" },
      { sno: "21", name: "Dr. Anup Kumar Chaudhary", designation: "Junior Resident" },
      { sno: "22", name: "Dr. Balduri srikanth", designation: "Junior Resident" },
      { sno: "23", name: "Dr. Mohd. Shoheb", designation: "Junior Resident" },
      { sno: "24", name: "Dr. Rishab Jaiswal", designation: "Junior Resident" },
      { sno: "25", name: "Dr. Kushumlata Yadav", designation: "Junior Resident" }
    ]
  },
  {
    department: "TB & Chest (Respiratory Medicine)",
    members: [
      { sno: "1", name: "Prof. G. N. Srivastava", designation: "Professor", image: "Prof (Dr.) G N Srivastava.webp" },
      { sno: "2", name: "Dr. Abdul Wahab Mirza", designation: "Associate Professor" },
      { sno: "3", name: "Dr. Vinod Kumar", designation: "Associate Professor" },
      { sno: "4", name: "Dr. Bavaliya D Dhirubhai", designation: "Senior Resident" },
      { sno: "5", name: "Dr. Asma Habib", designation: "Junior Resident" },
      { sno: "6", name: "Dr. Eblow Choudhary", designation: "Junior Resident" },
      { sno: "7", name: "Dr. Lodhiya Vihar Dinesh", designation: "Junior Resident" },
      { sno: "8", name: "Dr. Varun Gupta", designation: "Junior Resident" },
      { sno: "9", name: "Dr. Sharma Akshay Pravin", designation: "Junior Resident" },
      { sno: "10", name: "Dr. Jasmine", designation: "Junior Resident" },
      { sno: "11", name: "Dr. Shweta", designation: "Junior Resident" },
      { sno: "12", name: "Dr. Arif Qureshi", designation: "Junior Resident" },
      { sno: "13", name: "Dr. Siddharth Mishra", designation: "Junior Resident" }
    ]
  },
  {
    department: "Dermatology Venereology & Leprosy",
    members: [
      { sno: "1", name: "-", designation: "Professor" },
      { sno: "2", name: "Dr. Rashmi Singhl", designation: "Associate Professor", image: "Dr. Rashmi Singh.webp" },
      { sno: "3", name: "Dr. Mughda Kulkarni", designation: "Assistant Professor" },
      { sno: "4", name: "Dr. Pankhuri Agarwal", designation: "Senior Resident" },
      { sno: "5", name: "Dr. Srishti Singh", designation: "Junior Resident" }
    ]
  },
  {
    department: "Psychiatry",
    members: [
      { sno: "1", name: "-", designation: "Professor" },
      { sno: "2", name: "Dr. Mohit Saini", designation: "Associate Professor" },
      { sno: "3", name: "Dr. Suchi Pande", designation: "Assistant Professor" },
      { sno: "4", name: "Dr. Manishit Singh", designation: "Senior Resident" },
      { sno: "5", name: "Dr. Pratiksha Patel", designation: "Junior Resident" }
    ]
  },
  {
    department: "General Surgery",
    members: [
      { sno: "1", name: "Prof.(Dr.) V K Dixit", designation: "Professor", image: "Prof.(Dr.) V K Dixit.webp" },
      { sno: "2", name: "Dr. Saurabh Agarwal", designation: "Professor", image: "Prof.(Dr.) Saurabh Agrawal.webp" },
      { sno: "3", name: "Dr. Sanjay Prasad", designation: "Professor" },
      { sno: "4", name: "Dr. Alok Tripathi", designation: "Professor" },
      { sno: "5", name: "Dr. Girish Pandey", designation: "Professor" },
      { sno: "6", name: "Dr. Shivji S Ghose", designation: "Associate Professor" },
      { sno: "7", name: "Dr. Mayank Mishra", designation: "Associate Professor" },
      { sno: "8", name: "Dr. Yashpal Zinda", designation: "Associate Professor" },
      { sno: "9", name: "Dr. Harendra Ojha", designation: "Assistant Professor", image: "Dr. Harendra Ojha.webp" },
      { sno: "10", name: "Dr. Devesh Nebhani", designation: "Assistant Professor" },
      { sno: "11", name: "Dr. Saumya Singh", designation: "Assistant Professor" },
      { sno: "12", name: "Dr. Neeraj Sharma", designation: "Assistant Professor", image: "Dr. Neeraj Sharma.webp" },
      { sno: "13", name: "Dr. Dhiraj V Khithani", designation: "Assistant Professor" },
      { sno: "14", name: "Dr. Aditya Narayan Chaudhary", designation: "Assistant Professor", image: "Dr. Aditya Narayan Choudhary.webp" },
      { sno: "15", name: "Dr. Amit Kumar Tiwari", designation: "Assistant Professor" },
      { sno: "16", name: "Dr. Neeraj Agrawal", designation: "Assistant Professor" },
      { sno: "17", name: "Dr. Alok Ojha", designation: "Assistant Professor", image: "Dr. Alok Ojha.webp" },
      { sno: "18", name: "Dr. Sanjeev Kumar", designation: "Assistant Professor" },
      { sno: "19", name: "Dr. Pushpendra Singh", designation: "Assistant Professor" },
      { sno: "20", name: "Dr. Shravan Mishra", designation: "Assistant Professor" },
      { sno: "21", name: "Dr. Ganesh Yadav", designation: "Assistant Professor" },
      { sno: "22", name: "Dr. Shashi", designation: "Assistant Professor" },
      { sno: "23", name: "Dr. Vinit", designation: "Senior Resident" },
      { sno: "24", name: "Dr. Dinesh Singh", designation: "Senior Resident" },
      { sno: "25", name: "Dr. Deepak Agrahari", designation: "Senior Resident" },
      { sno: "26", name: "Dr. Vijay", designation: "Senior Resident" },
      { sno: "27", name: "Dr. Prasanjit Singh", designation: "Senior Resident" },
      { sno: "28", name: "Dr. S. G. Imam", designation: "Senior Resident" },
      { sno: "29", name: "Dr. Deep Dhawan", designation: "Senior Resident" },
      { sno: "30", name: "Dr. Ajay Kumar", designation: "Junior Resident", image: "Dr. Ajay Kumar Pandey.webp" },
      { sno: "31", name: "Dr. Archee", designation: "Junior Resident" },
      { sno: "32", name: "Dr. Ritu Yadav", designation: "Junior Resident" },
      { sno: "33", name: "Dr. Rakesh Kumar", designation: "Junior Resident" },
      { sno: "34", name: "Dr. Jyoti Kumari", designation: "Junior Resident" },
      { sno: "35", name: "Dr. Chandan Kumar Mishra", designation: "Junior Resident" },
      { sno: "36", name: "Dr. Ashish Kumar Singh", designation: "Junior Resident" },
      { sno: "37", name: "Tiwari Sachin Mahendra", designation: "Junior Resident" },
      { sno: "38", name: "Dr. Prabhakar Indrajeet", designation: "Junior Resident" },
      { sno: "39", name: "Dr. Ashutosh", designation: "Junior Resident" },
      { sno: "40", name: "Dr. Manish", designation: "Junior Resident" },
      { sno: "41", name: "Dr. Vijayee Gupta", designation: "Junior Resident" },
      { sno: "42", name: "Dr. Vijitash Maurya", designation: "Junior Resident" },
      { sno: "43", name: "Dr. Shrey Gupta", designation: "Junior Resident" }
    ]
  },
  {
    department: "Orthopedics",
    members: [
      { sno: "1", name: "Prof. S. K. Saraf", designation: "Professor", image: "Prof.(Dr.) S. K. Saraf.webp" },
      { sno: "2", name: "Prof. Amit Rastogi", designation: "Professor", image: "Prof.(Dr.) Amit Rastogi.webp" },
      { sno: "3", name: "Dr. Rakesh Bhuval Singh", designation: "Associate Professor" },
      { sno: "4", name: "Dr. S. K. Singh", designation: "Associate Professor" },
      { sno: "5", name: "Dr. U B Yadav", designation: "Associate Professor" },
      { sno: "6", name: "Dr. Biren Sukhabhai", designation: "Associate Professor" },
      { sno: "7", name: "Dr. Pankaj Kumar Singh", designation: "Associate Professor" },
      { sno: "8", name: "Dr. Niket Raj Garg", designation: "Associate Professor" },
      { sno: "9", name: "Dr. Avinash Dwivedi", designation: "Assistant Professor" },
      { sno: "10", name: "Dr. Piyush", designation: "Assistant Professor" },
      { sno: "11", name: "Dr. Rakesh Pareek", designation: "Assistant Professor" },
      { sno: "12", name: "Dr. Rohit", designation: "Assistant Professor" },
      { sno: "13", name: "Dr. Vishwanath Singh", designation: "Assistant Professor" },
      { sno: "14", name: "Dr. Avinash Kumar Singh", designation: "Assistant Professor" },
      { sno: "15", name: "Dr. Akhilesh kushwaha", designation: "Senior Resident" },
      { sno: "16", name: "Dr. Harshit Patel", designation: "Senior Resident" },
      { sno: "17", name: "Dr. Ananad Saurabh", designation: "Senior Resident" },
      { sno: "18", name: "Dr. Deepak Kumar", designation: "Junior Resident" },
      { sno: "19", name: "Dr. Mohd Sadab Khan", designation: "Junior Resident" },
      { sno: "20", name: "Dr. Rohan Yadav", designation: "Junior Resident" },
      { sno: "21", name: "Dr. Ajay Singla", designation: "Junior Resident" },
      { sno: "22", name: "Dr. Vachan Goyal", designation: "Junior Resident" },
      { sno: "23", name: "Dr. Ankit Anand", designation: "Junior Resident" },
      { sno: "24", name: "Dr. Pahul Bansal", designation: "Junior Resident" },
      { sno: "25", name: "Dr. Dinesh Kumar Chaturvedi", designation: "Junior Resident" },
      { sno: "26", name: "Dr. Ambuj Mittal", designation: "Junior Resident" }
    ]
  },
  {
    department: "ENT",
    members: [
      { sno: "1", name: "Dr. Shrawin Singh", designation: "Professor", image: "Prof.(Dr.) Shrawin Singh.webp" },
      { sno: "2", name: "Dr. Anup M", designation: "Professor" },
      { sno: "3", name: "Dr. Uday Kumar", designation: "Associate Professor" },
      { sno: "4", name: "Dr. Krishna Kumar Tiwari", designation: "Assistant Professor" },
      { sno: "5", name: "Dr. Manish", designation: "Assistant Professor" },
      { sno: "6", name: "Dr. Harsh", designation: "Assistant Professor" },
      { sno: "7", name: "Dr. Saurabh Gupta", designation: "Senior Resident" },
      { sno: "8", name: "Dr. Nidhi", designation: "Senior Resident" },
      { sno: "9", name: "Dr. Jaishree Gupta", designation: "Junior Resident" },
      { sno: "10", name: "Dr. Nidhi", designation: "Junior Resident" },
      { sno: "11", name: "Dr. Aishwarya Seth", designation: "Junior Resident" },
      { sno: "12", name: "Dr. Priyanka Tiwari", designation: "Junior Resident" },
      { sno: "13", name: "Dr. Minu S Kumar", designation: "Junior Resident" },
      { sno: "14", name: "Dr. Sudeshna Bandyopadhyay", designation: "Junior Resident" }
    ]
  },
  {
    department: "Ophthalmology",
    members: [
      { sno: "1", name: "Dr. Garima Rai", designation: "Professor", image: "Prof.(Dr.) Garima Rai.webp" },
      { sno: "2", name: "Dr. O. P. S. Maurya", designation: "Professor", image: "Prof.(Dr) Om Prakash Maurya.webp" },
      { sno: "3", name: "Dr. Haroon", designation: "Associate Professor" },
      { sno: "4", name: "Dr. Gunjan Rana", designation: "Assistant Professor" },
      { sno: "5", name: "Dr. Shraddha Pandey", designation: "Assistant Professor" },
      { sno: "6", name: "Dr. Surabhi", designation: "Assistant Professor" },
      { sno: "7", name: "Dr. Sakshi Singh", designation: "Senior Resident" },
      { sno: "8", name: "Dr. Shweta Pandey", designation: "Senior Resident" },
      { sno: "9", name: "Dr. Ankit Raj", designation: "Junior Resident" },
      { sno: "10", name: "Dr. Bibhash Kumar Annu", designation: "Junior Resident" },
      { sno: "11", name: "Dr. Kumar Harsh", designation: "Junior Resident" },
      { sno: "12", name: "Dr. Naisugik Choundwal", designation: "Junior Resident" },
      { sno: "13", name: "Dr. Sharleen Khan", designation: "Junior Resident" },
      { sno: "14", name: "Dr. Neha Biswas", designation: "Junior Resident" }
    ]
  },
  {
    department: "OBG",
    members: [
      { sno: "1", name: "Dr. Madhu Jain", designation: "Professor", image: "Prof.(Dr.) Madhu Jain.webp" },
      { sno: "2", name: "Dr. S. K. Ghosh", designation: "Professor" },
      { sno: "3", name: "Dr. Priyali", designation: "Professor" },
      { sno: "4", name: "Dr. Lavanya Anuranjani", designation: "Associate Professor", image: "Dr. Lavanya Anuranjani.webp" },
      { sno: "5", name: "Dr. Manjari Gupta", designation: "Associate Professor" },
      { sno: "6", name: "Dr. Soumya shree Pandhan", designation: "Assistant Professor" },
      { sno: "7", name: "Dr. Yashi", designation: "Assistant Professor" },
      { sno: "8", name: "Dr. Swati Gupta", designation: "Assistant Professor" },
      { sno: "9", name: "Dr. Pooja Maurya", designation: "Assistant Professor" },
      { sno: "10", name: "Dr. Renu", designation: "Assistant Professor" },
      { sno: "11", name: "Dr. Shagun Tiwari", designation: "Assistant Professor" },
      { sno: "12", name: "Dr. Vibha Mishra", designation: "Assistant Professor", image: "Dr. Vibha Mishra.webp" },
      { sno: "13", name: "Dr. Tejsa Mishra", designation: "Senior Resident" },
      { sno: "14", name: "Dr. Yashashwi Pandey", designation: "Senior Resident" },
      { sno: "15", name: "Dr. Azme Zehra", designation: "Senior Resident" },
      { sno: "16", name: "Dr. Pritha", designation: "Senior Resident" },
      { sno: "17", name: "Dr. Deepak Singh Jadaun", designation: "Junior Resident" },
      { sno: "18", name: "Dr. Gopika Ambat", designation: "Junior Resident" },
      { sno: "19", name: "Dr. Prerna Priya", designation: "Junior Resident" },
      { sno: "20", name: "Dr. Prachi", designation: "Junior Resident" },
      { sno: "21", name: "Dr. Gaurishetty Vinisha", designation: "Junior Resident" },
      { sno: "22", name: "Dr. Anagha S Bagi", designation: "Junior Resident" },
      { sno: "23", name: "Dr. Anita Thakur", designation: "Junior Resident" },
      { sno: "24", name: "Dr. Patel Mit Alpesh Kumar", designation: "Junior Resident" },
      { sno: "25", name: "Dr. Shubhi Vaishya", designation: "Junior Resident" }
    ]
  },
  {
    department: "Anesthesia",
    members: [
      { sno: "1", name: "Prof. Pushakar Ranjan", designation: "Professor" },
      { sno: "2", name: "Dr. Akhilesh Mishra", designation: "Associate Professor" },
      { sno: "3", name: "Dr. Sulakshna", designation: "Associate Professor" },
      { sno: "4", name: "Dr. R. K. Chaubey", designation: "Associate Professor" },
      { sno: "5", name: "Dr. Anil Kumar", designation: "Associate Professor" },
      { sno: "6", name: "Dr. Deepsikha", designation: "Assistant Professor" },
      { sno: "7", name: "Dr. Satish Patel", designation: "Assistant Professor" },
      { sno: "8", name: "Dr. Nishant Mishra", designation: "Assistant Professor" },
      { sno: "9", name: "Dr. Ankur", designation: "Assistant Professor" },
      { sno: "10", name: "Dr. Komal Paswan", designation: "Assistant Professor" },
      { sno: "11", name: "Dr. Arun Tiwari", designation: "Assistant Professor" },
      { sno: "12", name: "Dr. Rahul Singh", designation: "Assistant Professor" },
      { sno: "13", name: "Dr. Uma Kant", designation: "Senior Resident" },
      { sno: "14", name: "Dr. Priya Ranjan", designation: "Senior Resident" },
      { sno: "15", name: "Dr. Khushbu Manubhai Patel", designation: "Senior Resident" },
      { sno: "16", name: "Dr. Priya Singh", designation: "Junior Resident" },
      { sno: "17", name: "Dr. Mandly Raghunath", designation: "Junior Resident" },
      { sno: "18", name: "Dr. Nidhi", designation: "Junior Resident" },
      { sno: "19", name: "Dr. Emmanual Kuruvilla", designation: "Junior Resident" },
      { sno: "20", name: "Dr. Vivek Kumar", designation: "Junior Resident" },
      { sno: "21", name: "Dr. Akriti Sinha", designation: "Junior Resident" },
      { sno: "22", name: "Dr. Shreay Gaikwad", designation: "Junior Resident" },
      { sno: "23", name: "Dr. Tanvi Anand", designation: "Junior Resident" },
      { sno: "24", name: "Dr. Deepa Rampuria", designation: "Junior Resident" },
      { sno: "25", name: "Dr. Abhikanksha", designation: "Junior Resident" },
      { sno: "26", name: "Dr. Shripati Tripathi", designation: "Junior Resident" },
      { sno: "27", name: "Dr. Rajanikant Shandilya", designation: "Junior Resident" },
      { sno: "28", name: "Dr. Abhinav Singh", designation: "Junior Resident" },
      { sno: "29", name: "Dr. Lucky Gaurav Sachan", designation: "Junior Resident" },
      { sno: "30", name: "Dr. Kajal", designation: "Junior Resident" }
    ]
  },
  {
    department: "Radiology",
    members: [
      { sno: "1", name: "Prof. Gaurav Sharma", designation: "Professor" },
      { sno: "2", name: "Dr. Preeti Kapoor", designation: "Professor" },
      { sno: "3", name: "Dr. Pragya Ghosh", designation: "Associate Professor" },
      { sno: "4", name: "Dr. Ankit Patel", designation: "Assistant Professor" },
      { sno: "5", name: "Dr. Pankaj Das", designation: "Assistant Professor" },
      { sno: "6", name: "Dr. Renu", designation: "Senior Resident" },
      { sno: "7", name: "Dr. Saurabh Maganbhai Patel", designation: "Senior Resident" },
      { sno: "8", name: "Dr. Kamlesh", designation: "Senior Resident" },
      { sno: "9", name: "Dr. Sunny Gupta", designation: "Junior Resident" },
      { sno: "10", name: "Dr. Arnab Choudhary", designation: "Junior Resident" },
      { sno: "11", name: "Dr. Varun CR", designation: "Junior Resident" },
      { sno: "12", name: "Dr. Samarpan Raheja", designation: "Junior Resident" },
      { sno: "13", name: "Dr. Kanwalpreet Singh", designation: "Junior Resident" },
      { sno: "14", name: "Dr. Shaikh Faizan", designation: "Junior Resident" },
      { sno: "15", name: "Dr. Bhupesh Goyal", designation: "Junior Resident" },
      { sno: "16", name: "Dr. Prawal Pratap Singh", designation: "Junior Resident" }
    ]
  },
  {
    department: "Dentistry",
    members: [
      { sno: "1", name: "Dr. Vishal Singh", designation: "Professor", image: "Prof.(Dr.) Vishal Singh.webp" },
      { sno: "2", name: "Dr. Ravi", designation: "Associate Professor", image: "Dr. Ravi.webp" },
      { sno: "3", name: "Dr. Abhishek das", designation: "Assistant Professor", image: "Dr. Abhishek Das.webp" },
      { sno: "4", name: "Dr. Sweta Pujan", designation: "Senior Resident" },
      { sno: "5", name: "Dr. Mohd Zahid Khan", designation: "Junior Resident" },
      { sno: "6", name: "Dr. Akrity", designation: "Junior Resident" }
    ]
  },
  {
    department: "Anatomy",
    members: [
      { sno: "1", name: "Dr. S. K. Pandey", designation: "Professor" },
      { sno: "2", name: "Dr. Vipin", designation: "Professor" },
      { sno: "3", name: "Dr. Sajjad", designation: "Associate Professor" },
      { sno: "4", name: "Dr. Archana", designation: "Assistant Professor" },
      { sno: "5", name: "Dr. Rahul Rai", designation: "Assistant Professor" },
      { sno: "6", name: "Dr. Rubi", designation: "Assistant Professor" },
      { sno: "7", name: "Dr. Harsh Ranjan", designation: "Tutor" },
      { sno: "8", name: "Dr. Kanika", designation: "Tutor" },
      { sno: "9", name: "Dr. Brijesh Kumar Bhardwaj", designation: "Tutor" },
      { sno: "10", name: "Dr. Padmannabh", designation: "Tutor" },
      { sno: "11", name: "Dr. Manish Upadhyay", designation: "Tutor" }
    ]
  },
  {
    department: "Physiology",
    members: [
      { sno: "1", name: "Dr. P. Prashant", designation: "Professor" },
      { sno: "2", name: "Dr. Sonu Ajmani", designation: "Associate Professor" },
      { sno: "3", name: "Dr. Sandeep H Ghuge", designation: "Associate Professor" },
      { sno: "4", name: "Dr. Sharad Kumar", designation: "Assistant Professor" },
      { sno: "5", name: "Dr. Ramakrishna Waghai", designation: "Assistant Professor" },
      { sno: "6", name: "Dr. Anurag Singh", designation: "Tutor" },
      { sno: "7", name: "Dr. Shreeya", designation: "Tutor" },
      { sno: "8", name: "Dr. Vishal Yadav", designation: "Tutor" }
    ]
  },
  {
    department: "Biochemistry",
    members: [
      { sno: "1", name: "Dr. Ketki Khandhadiya", designation: "Professor" },
      { sno: "2", name: "Dr. Atul Agte", designation: "Associate Professor" },
      { sno: "3", name: "Dr. Shailja Shrestha", designation: "Associate Professor" },
      { sno: "4", name: "Dr. Arpita Mishra", designation: "Assistant Professor" },
      { sno: "5", name: "Dr. Ajeet yadav", designation: "Assistant Professor" },
      { sno: "6", name: "Dr. Sharad Singh", designation: "Assistant Professor" },
      { sno: "7", name: "Dr. Akanksha Gupta", designation: "Senior Resident" },
      { sno: "8", name: "Dr. Ujala", designation: "Tutor" },
      { sno: "9", name: "Dr. Amit Kumar Yadav", designation: "Tutor" },
      { sno: "10", name: "Dr. Umesh Kumar", designation: "Tutor" }
    ]
  },
  {
    department: "Pharmacology",
    members: [
      { sno: "1", name: "Dr. Sandeep Kumar Gupta", designation: "Professor" },
      { sno: "2", name: "Dr. Vaidya Kesha", designation: "Associate Professor" },
      { sno: "3", name: "Dr. Bhargav Roy", designation: "Associate Professor" },
      { sno: "4", name: "Dr. Ravi Sharma", designation: "Associate Professor" },
      { sno: "5", name: "Dr. Kriti Pandey", designation: "Assistant Professor" },
      { sno: "6", name: "Dr. Gira Sulabh", designation: "Assistant Professor" },
      { sno: "7", name: "Dr. Kunal Ganpatbhai", designation: "Assistant Professor" },
      { sno: "8", name: "Dr. Shweta", designation: "Tutor" },
      { sno: "9", name: "Dr. Prashant R", designation: "Tutor" },
      { sno: "10", name: "Dr. Sagrika Rai", designation: "Tutor" },
      { sno: "11", name: "Dr. Anita Srivastava", designation: "Tutor" },
      { sno: "12", name: "Dr. Twinkle Singh", designation: "Tutor" },
      { sno: "13", name: "Dr. Priyambada", designation: "Tutor" }
    ]
  },
  {
    department: "Pathology",
    members: [
      { sno: "1", name: "Dr. Ajamal Sing Bhayal", designation: "Professor" },
      { sno: "2", name: "Dr. Neeraj Kumar Singh", designation: "Associate Professor" },
      { sno: "3", name: "Dr. Vatsala Kishore", designation: "Associate Professor" },
      { sno: "4", name: "Dr. Priyankar", designation: "Associate Professor" },
      { sno: "5", name: "Dr. Tanvi Palival", designation: "Associate Professor" },
      { sno: "6", name: "Dr. Uma Shankar Gupta", designation: "Assistant Professor" },
      { sno: "7", name: "Dr. Saumya", designation: "Assistant Professor" },
      { sno: "8", name: "Dr. ILa Singh", designation: "Assistant Professor" },
      { sno: "9", name: "Dr. Pallavi", designation: "Assistant Professor" },
      { sno: "10", name: "Dr. Nidhis Kumar", designation: "Assistant Professor" },
      { sno: "11", name: "Dr. Anuj Pandey", designation: "Tutor" },
      { sno: "12", name: "Dr. Pooja Awasthi", designation: "Tutor" },
      { sno: "13", name: "Dr. Durgeshwari", designation: "Tutor" },
      { sno: "14", name: "Dr. Sanjay Kumar", designation: "Tutor" },
      { sno: "15", name: "Dr. Ankansha Anu", designation: "Tutor" },
      { sno: "16", name: "Dr. Rohit Sharma", designation: "Tutor" },
      { sno: "17", name: "Dr. Shivabhallava", designation: "Tutor" },
      { sno: "18", name: "Dr. Ankit Singh", designation: "Tutor" },
      { sno: "19", name: "Dr. Priyanka Kumari", designation: "Tutor" },
      { sno: "20", name: "Dr. Kumari Diksha", designation: "Tutor" },
      { sno: "21", name: "Dr. Apurva Raj", designation: "Tutor" },
      { sno: "22", name: "Dr. Shipra Tiwari", designation: "Tutor" },
      { sno: "23", name: "Dr. Sujata Rani", designation: "Tutor" }
    ]
  },
  {
    department: "Microbiology",
    members: [
      { sno: "1", name: "Dr. K. K. Lahiri", designation: "Professor" },
      { sno: "2", name: "Dr. Asim Singh", designation: "Professor" },
      { sno: "3", name: "Dr. Sudha K Mishra", designation: "Associate Professor" },
      { sno: "4", name: "Dr. Shalini Singh", designation: "Associate Professor" },
      { sno: "5", name: "Dr. Mahak Jain", designation: "Assistant Professor" },
      { sno: "6", name: "Dr. Mukesh Kr Singh", designation: "Assistant Professor" },
      { sno: "7", name: "Dr. Anup K Singh", designation: "Tutor" },
      { sno: "8", name: "Dr. Ekta Rani", designation: "Tutor" },
      { sno: "9", name: "Dr. Divya Thakur", designation: "Tutor" },
      { sno: "10", name: "Dr. Debasish Paul", designation: "Tutor" }
    ]
  },
  {
    department: "Forensic Medicine",
    members: [
      { sno: "1", name: "Dr. Shailesh Kumar", designation: "Professor" },
      { sno: "2", name: "Dr. Amit Kochar", designation: "Professor" },
      { sno: "3", name: "Dr. Rohit Singh", designation: "Tutor" },
      { sno: "4", name: "Dr. Abhinya Srivastava", designation: "Tutor" },
      { sno: "5", name: "Dr. Pooja Singh", designation: "Tutor" },
      { sno: "6", name: "Dr. Sudhir Jaiswal", designation: "Tutor" }
    ]
  },
  {
    department: "Community Medicine",
    members: [
      { sno: "1", name: "Dr. C. P. Mishra", designation: "Professor" },
      { sno: "2", name: "Dr. V. K. Mehta", designation: "Professor" },
      { sno: "3", name: "Dr. Dheeraj Sharma", designation: "Associate Professor" },
      { sno: "4", name: "Dr. Tapan Mandal", designation: "Associate Professor" },
      { sno: "5", name: "Dr. Manu uppal", designation: "Assistant Professor" },
      { sno: "6", name: "Dr. Rajendra Narayan", designation: "Assistant Professor" },
      { sno: "7", name: "Dr. Saumya Srivastava", designation: "Assistant Professor" },
      { sno: "8", name: "Dr. Anjali", designation: "Assistant Professor" },
      { sno: "9", name: "Dr. Ayub Khan", designation: "Statistician" },
      { sno: "10", name: "Dr. Aniwarya Bhaskar", designation: "Tutor" },
      { sno: "11", name: "Dr. Divyanshi", designation: "Tutor" },
      { sno: "12", name: "Dr. RituKant", designation: "Tutor" },
      { sno: "13", name: "Dr. Prachi", designation: "Tutor" },
      { sno: "14", name: "Dr. Rajan Singh", designation: "Tutor" },
      { sno: "15", name: "Dr. Richa Singh", designation: "Tutor" }
    ]
  },
  {
    department: "Emergency Medicine",
    members: [
      { sno: "1", name: "Dr. Bikram Gupta", designation: "Professor" },
      { sno: "2", name: "Dr. Ganesh Raghunath Khade", designation: "Associate Professor" },
      { sno: "3", name: "Dr. Charu Shekhar", designation: "Assistant Professor" },
      { sno: "4", name: "Dr. Ashutosh Singh", designation: "Senior Resident" },
      { sno: "5", name: "Dr. Pandav Krunal Damjibhai", designation: "Senior Resident" },
      { sno: "6", name: "Dr. Dhawal Prajapati", designation: "Senior Resident" },
      { sno: "7", name: "Dr. Chandan K Jaiswal", designation: "Senior Resident" },
      { sno: "8", name: "Dr. Anurag Rai", designation: "Senior Resident" },
      { sno: "9", name: "Dr. Ashutosh Tiwari", designation: "Senior Resident" },
      { sno: "10", name: "Dr. Pankaj Khatri", designation: "Senior Resident" },
      { sno: "11", name: "Dr. Jaideep Himmatbhai", designation: "Senior Resident" }
    ]
  }
];
