export const topFacultyData = [
  { "name": "Dr. Abhishek Das", "image": "Dr. Abhishek Das.webp", "designation": "Consultant (Oral Oncologist)" },
  { "name": "Dr. Aditya Narayan Choudhary", "image": "Dr. Aditya Narayan Choudhary.webp", "designation": "Plastic Surgeon" },
  { "name": "Dr. Ajay Kumar Pandey", "image": "Dr. Ajay Kumar Pandey.webp", "designation": "Sr. Cardiologist" },
  { "name": "Dr. Alok Ojha", "image": "Dr. Alok Ojha.webp", "designation": "Sr. Neuro Surgeon" },
  { "name": "Dr. Harendra Ojha", "image": "Dr. Harendra Ojha.webp", "designation": "Sr. Cardiac Surgeon" },
  { "name": "Dr. Harmohan Saho", "image": "Dr. Harmohan Saho.webp", "designation": "Consultant (Neuro Medicine)" },
  { "name": "Dr. Lavanya Anuranjani", "image": "Dr. Lavanya Anuranjani.webp", "designation": "Consultant (OBGY)" },
  { "name": "Dr. Neeraj Sharma", "image": "Dr. Neeraj Sharma.webp", "designation": "Neuro Surgeon Consultant" },
  { "name": "Dr. Nilesh Kumar Rai", "image": "Dr. Nilesh Kumar Rai.webp", "designation": "Gastroenterology" },
  { "name": "Dr. Parul Raj", "image": "Dr. Parul Raj.webp", "designation": "MPT, Ph.D., FAGE" },
  { "name": "Dr. Rashmi Singh", "image": "Dr. Rashmi Singh.webp", "designation": "Dermatologist" },
  { "name": "Dr. Ravi", "image": "Dr. Ravi.webp", "designation": "Maxillofacial Surgery" },
  { "name": "Dr. Sanjeev Sharma", "image": "Dr. Sanjeev Sharma.webp", "designation": "Sr. Plastic Surgeon" },
  { "name": "Dr. Vibha Mishra", "image": "Dr. Vibha Mishra.webp", "designation": "Consultant (Obstetrics and Gynecology)" },
  { "name": "Dr. Yogesh Kumar Gaur", "image": "Dr. Yogesh Kumar Gaur.webp", "designation": "Consultant (Nephrologist)" },
  { "name": "Prof (Dr.) G N Srivastava", "image": "Prof (Dr.) G N Srivastava.webp", "designation": "Sr. Consultant" },
  { "name": "Prof.(Dr) Om Prakash Maurya", "image": "Prof.(Dr) Om Prakash Maurya.webp", "designation": "Sr. Consultant" },
  { "name": "Prof.(Dr) Pradeep Jain", "image": "Prof.(Dr) Pradeep Jain.webp", "designation": "Sr. Consultant" },
  { "name": "Prof.(Dr.) Amit Rastogi", "image": "Prof.(Dr.) Amit Rastogi.webp", "designation": "Professor Orthopaedics" },
  { "name": "Prof.(Dr.) Garima Rai", "image": "Prof.(Dr.) Garima Rai.webp", "designation": "Sr. Consultant" },
  { "name": "Prof.(Dr.) M. S. I. Siddiqui", "image": "Prof.(Dr.) M. S. I. Siddiqui.webp", "designation": "HOD Of General Medicine" },
  { "name": "Prof.(Dr.) Madhu Jain", "image": "Prof.(Dr.) Madhu Jain.webp", "designation": "Sr. Consultant (Obs & gynae)" },
  { "name": "Prof.(Dr.) Madhukar Rai", "image": "Prof.(Dr.) Madhukar Rai.webp", "designation": "Endocrinology" },
  { "name": "Prof.(Dr.) O. P. Mishra", "image": "Prof.(Dr.) O. P. Mishra.webp", "designation": "Sr. Consultant" },
  { "name": "Prof.(Dr.) Rana Gopal Singh", "image": "Prof.(Dr.) Rana Gopal Singh.webp", "designation": "Sr. Consultant (Nephrology)" },
  { "name": "Prof.(Dr.) S K Singh", "image": "Prof.(Dr.) S K Singh.webp", "designation": "Senior Endocrinologist" },
  { "name": "Prof.(Dr.) S. C. Goel", "image": "Prof.(Dr.) S. C. Goel.webp", "designation": "Ex. Prof. & HOD of Orthopaedics IMS" },
  { "name": "Prof.(Dr.) S. K. Saraf", "image": "Prof.(Dr.) S. K. Saraf.webp", "designation": "Sr. Consultant" },
  { "name": "Prof.(Dr.) Saurabh Agrawal", "image": "Prof.(Dr.) Saurabh Agrawal.webp", "designation": "HOD Of General Surgery" },
  { "name": "Prof.(Dr.) Shrawin Singh", "image": "Prof.(Dr.) Shrawin Singh.webp", "designation": "Head of department (ENT)" },
  { "name": "Prof.(Dr.) V K Dixit", "image": "Prof.(Dr.) V K Dixit.webp", "designation": "Senior Gastroenterologist" },
  { "name": "Prof.(Dr.) Vishal Singh", "image": "Prof.(Dr.) Vishal Singh.webp", "designation": "Prosthodontics" }
];
